export const WS_PROFILE_ORDERS_START = 'WS_PROFILE_ORDERS_START';
export const WS_PROFILE_ORDERS_SUCCESS = 'WS_PROFILE_ORDERS_SUCCESS';
export const WS_PROFILE_ORDERS_MESSAGE = 'GET_PROFILE_ORDERS';
export const WS_PROFILE_ORDERS_SEND = 'WS_PROFILE_ORDERS_SEND';
export const WS_PROFILE_ORDERS_CLOSED = 'WS_PROFILE_ORDERS_CLOSED';
export const WS_PROFILE_ORDERS_FAILED = 'GET_PROFILE_ORDERS_FAILED';

