export const WS_PROFILE_ORDERS_START = 'WS_PROFILE_ORDERS_START';
export const WS_PROFILE_ORDERS_SUCCESS = 'WS_PROFILE_ORDERS_SUCCESS';
export const WS_PROFILE_ORDERS_MESSAGE = 'WS_PROFILE_ORDERS_MESSAGE';
export const WS_PROFILE_ORDERS_SEND = 'WS_PROFILE_ORDERS_SEND';
export const WS_PROFILE_ORDERS_CLOSED = 'WS_PROFILE_ORDERS_CLOSED';
export const WS_PROFILE_ORDERS_FAILED = 'WS_PROFILE_ORDERS_FAILED';

export const CLOSE_PROFILE_ORDERS_WS = 'CLOSE_PROFILE_ORDERS_WS'

