export const AUTH_PROCESS: 'AUTH_PROCESS' = 'AUTH_PROCESS';
export const AUTH_SUCCESS: 'AUTH_SUCCESS' = 'AUTH_SUCCESS';
export const AUTH_FAILED: 'AUTH_FAILED' = 'AUTH_FAILED';
export const AUTH_RESET: 'AUTH_RESET' = 'AUTH_RESET';