export const SET_BUN: "SET_BUN" = "SET_BUN";
export const SET_INGREDIENTS: "SET_INGREDIENTS" = "SET_INGREDIENTS";

export const CALC_FULLPRICE: "CALC_FULLPRICE" = "CALC_FULLPRICE";
export const CALC_ID: "CALC_ID" = "CALC_ID";

export const SET_ORDER_ID: "SET_ORDER_ID" = "SET_ORDER_ID";

export const ON_BUN_DROP: "ON_BUN_DROP" = "ON_BUN_DROP";
export const ON_MAIN_DROP: "ON_MAIN_DROP" = "ON_MAIN_DROP";

export const DELETE_ITEM: "DELETE_ITEM" = "DELETE_ITEM";
export const REFILL_CONSTRUCTOR: "REFILL_CONSTRUCTOR" = "REFILL_CONSTRUCTOR";
