export const REQUEST_NEW_PASS: 'REQUEST_NEW_PASS' = 'REQUEST_NEW_PASS';
export const REQUEST_NEW_PASS_SUCCESS: 'REQUEST_NEW_PASS_SUCCESS' = 'REQUEST_NEW_PASS_SUCCESS';
export const REQUEST_NEW_PASS_FAILED: 'REQUEST_NEW_PASS_FAILED' = 'REQUEST_NEW_PASS_FAILED';
export const REQUEST_NEW_PASS_RESET: 'REQUEST_NEW_PASS_RESET' = 'REQUEST_NEW_PASS_RESET';