export const LOG_IN_REQUEST: 'LOG_IN_REQUEST' = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS: 'LOG_IN_SUCCESS' = "LOG_IN_SUCCESS";
export const LOG_IN_FAILED: 'LOG_IN_FAILED' = "LOG_IN_FAILED";
export const LOG_IN_RESET: 'LOG_IN_RESET' = "LOG_IN_RESET";

export const UPDATE_ACCESS_TOKEN_REQUEST: 'UPDATE_ACCESS_TOKEN_REQUEST' = "UPDATE_ACCESS_TOKEN_REQUEST";
export const UPDATE_ACCESS_TOKEN_SUCCESS: 'UPDATE_ACCESS_TOKEN_SUCCESS' = "UPDATE_ACCESS_TOKEN_SUCCESS";
export const UPDATE_ACCESS_TOKEN_FAILED: 'UPDATE_ACCESS_TOKEN_FAILED' = "UPDATE_ACCESS_TOKEN_FAILED";