export const LOG_OUT: "LOG_OUT" = "LOG_OUT";
export const LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS" = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILED: "LOG_OUT_FAILED" = "LOG_OUT_FAILED";
export const LOG_OUT_RESET: "LOG_OUT_RESET" = "LOG_OUT_RESET";

export const GET_USER_INFO: "GET_USER_INFO" = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS" = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILED: "GET_USER_INFO_FAILED" = "GET_USER_INFO_FAILED";
export const USER_INFO_RESET: "USER_INFO_RESET" = "USER_INFO_RESET";

export const EDIT_USER_INFO: "EDIT_USER_INFO" = "EDIT_USER_INFO";
export const EDIT_USER_INFO_SUCCESS: "EDIT_USER_INFO_SUCCESS" = "EDIT_USER_INFO_SUCCESS";
export const EDIT_USER_INFO_FAILED: "EDIT_USER_INFO_FAILED" = "EDIT_USER_INFO_FAILED";